version: "3"

services:
  db:
    container_name: db_cashforce
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
      - 3360:3360
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - api_net

networks:
  api_net:
    driver: bridge
