version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: container_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33065:3306

  api:
    container_name: api
    image: node:16
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    tty: true 
    stdin_open: true 
    depends_on:
      - mysql